### PR TITLE
Hangar Real World Quick Start Tutorial

### PR DESCRIPTION
**Pull request by alessiamarcolini**
#### _Why is this change required? What problem does it solve?:_
New tutorial covering only the basic stuff for version 0.5 release, such as Repository creation and initialization, adding data to columns and committing changes.

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Documentation update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Is this PR ready for review, or a work in progress?
- [x] Ready for review
- [ ] Work in progress

## How Has This Been Tested?
Put an `x` in the boxes that apply:
- [x] Current tests cover modifications made
- [ ] New tests have been added to the test suite
- [ ] Modifications were made to existing tests to support these changes
- [ ] Tests may be needed, but they are not included when the PR was proposed
- [ ] I don't know. Help!

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](../CONTRIBUTING.rst)** document.
- [x] I have signed (or will sign when prompted) the tensorwork CLA.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alessiamarcolini** [comment]
Thank you @lantiga for the review!

I agree with the first point, I will change the name of the checkout object to `master`.
I'll add a comment to clarify that would be impractical for larger datasets.

Also, why are some tests failing?

**Comment by hhsecond** [comment]
@alessiamarcolini Tests are failing probably because of some version upgrade came to one of our test dependencies. Even the master is failing since last week. @rlizzo might have a clue

**Comment by lantiga** [comment]
No idea actually, @rlizzo ?

**Comment by elistevens** [comment]
Can I suggest `master_checkout` or `head_checkout`?  The term `master` by itself is also used for replication, and this helps make it clear that it's a `XxxCheckout` object.

When I've copied example code into other projects, reviewers have complained about it not being clear what `co` is.

Another idea: since there are many places in the API that only accept one or the other of reader or writer checkouts, perhaps the names should be `head_read_checkout` or `head_wcheckout` or something like that (I prefer the first, but it can get verbose).

**Comment by lantiga** [comment]
Hey @elistevens :-) What about `master_branch`? Wouldn't it be less confusing than `master_checkout`? IDK, `checkout` sounds so SVN-y

**Comment by elistevens** [comment]
If the object's class is `XxxCheckout` then I think that should be reflected in the name of the variable.

**Comment by lantiga** [comment]
> If the object's class is `XxxCheckout` then I think that should be reflected in the name of the variable.

Agreed. It goes both ways is guess 😜

**Comment by alessiamarcolini** [comment]
@rlizzo should be ready now :)

**Comment by rlizzo** [comment]
Looks good! Merging!

**Pull request merged**
