### PR TITLE
bug fix dataset conflict

### PR DESCRIPTION
**Pull request by hhsecond**
## Motivation and Context
There was a bug hidden in `dataset_conflicts` function which was letting the control-flow call `_schema_dict_to_nt` with a non-dictionary argument. We might have to start running mypy as part of CI

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Is this PR ready for review, or a work in progress?
- [x] Ready for review
- [ ] Work in progress

## How Has This Been Tested?
Put an `x` in the boxes that apply:
- [ ] Current tests cover modifications made
- [ ] New tests have been added to the test suite
- [ ] Modifications were made to existing tests to support these changes
- [x] Tests may be needed, but they are not included when the PR was proposed
- [ ] I don't know. Help!

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](../CONTRIBUTING.rst)** document.
- [x] I have signed (or will sign when prompted) the tensorwork CLA.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hhsecond** [comment]
@rlizzo I have tests in #76 that covers this as well

**Comment by rlizzo** [comment]
Nice catch sherin! Merging now!

**Comment by rlizzo** [comment]
apparently the mobile version of GitHub does not let you merge a branch when there are failing status checks? 
`

ecause the codecov report has a failing status?? Fairly certain that's a new

**Comment by hhsecond** [comment]
@rlizzo It looks like I don't have enough permission to merge.

**Comment by rlizzo** [comment]
ok. let's talk about that in the call

**Pull request merged**
